version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
    ignore:
      - dependency-name: "scipy"  # numba-scipy limit (<=1.6.2)
      - dependency-name: "numpy"  # numba limited
      - dependency-name: "neutronics-material-maker" # incompatible upgrade path
      - dependency-name: "nlopt"  # numpy limited
