repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: test_data
      - id: check-merge-conflict
      - id: end-of-file-fixer
        exclude: test_data
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: test_data

  - repo: https://github.com/astral-sh/ruff-pre-commit
<<<<<<< HEAD
<<<<<<< HEAD
    rev: v0.6.2
=======
    rev: v0.5.6
>>>>>>> 869259a7 (Bump ruff from 0.5.5 to 0.5.6 (#3501))
=======
    rev: v0.5.7
>>>>>>> 56b6c547 (Bump ruff from 0.5.6 to 0.5.7 (#3513))
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [json, yaml]
        args: [--tab-width=2]

  - repo: https://github.com/citation-file-format/cffconvert
    rev: 5295f87c0e261da61a7b919fc754e3a77edd98a7
    hooks:
      - id: validate-cff
