repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
      exclude: test_data
    - id: check-merge-conflict
    - id: end-of-file-fixer
      exclude: test_data
    - id: mixed-line-ending
      args: [--fix=lf]
      exclude: test_data

-   repo: https://github.com/pycqa/isort
    rev: 5.11.1
    hooks:
    - id: isort

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black
      language_version: python3.8

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      verbose: True
      additional_dependencies: [flake8-docstrings,  pep8-naming, flake8-bandit]
      args: [--exit-zero]

-   repo: local
    hooks:
    - id: regenerate-ipynb-examples
      name: regenerate-ipynb-examples
      entry: python examples/convert_py_to_ipynb.py
      language: system
      args: [--check]
      types: [python]
      files: ^examples/
      exclude: ^examples/convert_py_to_ipynb.py

-   repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
    - id: black-jupyter
      language_version: python3.8
      types: [jupyter]
