blank_issues_enabled: false
contact_links:
  - name: Bluemira Discussions
    url: https://github.com/Fusion-Power-Plant-Framework/bluemira/discussions
    about: For more abstract communications
  - name: Bluemira Matrix channel
    url: https://matrix.to/#/#bluemira:matrix.org
    about: Come chat with us on Matrix
