services:
  bluemira:
    image: <my_registry_url>:<port>/<DOCKER USER>/bluemira:latest
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix  # X11 forwarding
        - $HOME/.Xauthority:/user/.Xauthority  # X11 forwarding
        - /dev/dri/card0:/dev/dri/card0  # Removes cad viewer warning for me
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"
    cmd: /bin/bash

  bluemira_dev:
    image: <my_registry_url>:<port>/<DOCKER USER>/bluemira:dev
    extends:
      service: bluemira
    profiles: ['develop']
    volumes:
      - <bluemira_dir>:/home/user/bluemira
      - <process_dir>:/home/user/process
