FROM ubuntu:22.04

# disables weird keyboards checks
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y \
    python3-dev \
    python3-venv \
    build-essential \
    software-properties-common \
    cmake \
    git

RUN add-apt-repository ppa:freecad-maintainers/freecad-stable
RUN apt-get update
RUN apt-get install freecad -y

RUN apt-get install python3-pip -y

WORKDIR /home/user

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY requirements-develop.txt ./requirements-develop.txt
RUN pip install --no-cache-dir -r requirements-develop.txt

RUN pip install --no-cache-dir pytest-xdist

# Build and install fenics
COPY scripts/fenics ./scripts/fenics/
RUN bash scripts/fenics/install-fenics-deps.sh
RUN bash scripts/fenics/install-fenics.sh

# h5py is a dependency of meshio. We need to manually install it or we run into
# a segfault when meshio attempts to import it, even though we can import h5py
# separately without issue.
# see https://github.com/Fusion-Power-Plant-Framework/bluemira/issues/1258 and
# https://github.com/h5py/h5py/issues/695

RUN pip install Cython

RUN apt-get install -y libhdf5-dev
ENV HDF5_DIR /usr/lib/x86_64-linux-gnu/hdf5/serial/
# RUN pip install --global-option=build_ext git+https://github.com/h5py/h5py.git
RUN pip install --no-binary=h5py h5py
# RUN pip --no-cache-dir install h5py

# Dolfin needs help finding Boost runtime libaries
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

WORKDIR /home/user/app

COPY . .

RUN pip install --no-cache-dir -e .

COPY main.py .

# RUN useradd -ms /bin/bash user
# USER user

ENTRYPOINT [ "tail","-f", "/dev/null" ]
