services:
  bluemira:
    build:
      context: ../
      dockerfile: ./docker/env.Dockerfile
      target: release
    image: bluemira:release
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix  # X11 forwarding
        - $HOME/.Xauthority:/home/user/.Xauthority  # X11 forwarding
        - /dev/dri/card0:/dev/dri/card0  # Removes cad viewer warning for me
    environment:
      DISPLAY: $DISPLAY
    network_mode: host

  bluemira-develop:
   build:
      target: develop
   image: bluemira:develop
   extends:
     service: bluemira
   volumes:
     - ../:/home/user/bluemira
     - ../../process_dev:/home/user/process
