name: bluemira

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.8
  - pythonocc-core=7.4.1
  - freecad=0.19.2
  - freecad.python=0.0.3
  - gmsh=4.6.0
  - python-gmsh=4.6.0
  - meshio=4.4.5
  - mshr=2019.1.0
  - fenics=2019.1.0
  - numba=0.53.1
  - numpy=1.19.5
  - fluids=0.1.77
  - shapely=1.6.4
  - MeshPy=2018.2.1
  - pyside2=5.13.2
  - scipy=1.4.1
  - graphviz
  - pip=21.1.1
  - pip:
    - -r file:../requirements.txt
    - -r file:../requirements-develop.txt
