name: bluemira-conda

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.8
  - pythonocc-core=7.4.1
  - freecad=0.19.2
  - freecad.python=0.0.3
  - gmsh=4.6.0
  - python-gmsh=4.6.0
  - meshio=4.4.5
  - mshr=2019.1.0
  - fenics=2019.1.0
  - numba=0.53.1
  - numpy=1.19.5
  - fluids=0.1.77
  # - shapely=1.7.1  # conda cannot resolve 1.7.1, so installed from pypi
  - MeshPy=2018.2.1
  - pyside2=5.13.2
  - scipy=1.4.1
  - graphviz
  - anytree=2.8.0
  - appdirs=1.4.4
  - asteval=0.9.23
  - attrs=20.3.0
  - backcall=0.2.0
  - black=20.8b1
  - click=7.1.2
  - CoolProp=6.4.1
  - cycler=0.10.0
  - decorator=5.0.7
  - flake8=3.9.1
  - flake8-docstrings=1.6.0
  - imageio=2.9.0
  - importlib-metadata=4.0.1
  - iniconfig=1.1.1
  - ipykernel=5.5.3
  - ipython=7.16.1
  # - jedi=0.18.0  # Causes dependency resolution error
  - joblib=1.0.1
  - kiwisolver=1.3.1
  - llvmlite=0.36.0
  # - matplotlib=3.3.4  # Breaks plotting tests if installed from conda
  - natsort=7.1.1
  - nlopt=2.7.0
  - numba-scipy=0.3.0
  - numexpr=2.7.3
  - packaging=20.9
  - pandas=1.1.5
  # - parso=0.8.2  # Causes dependency resolution error
  - pep8-naming=0.11.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - Pillow=8.2.0
  - pluggy=0.13.1
  - pre-commit=2.12.1
  - prompt-toolkit=3.0.18
  - ptyprocess=0.7.0
  - py=1.10.0
  - pybind11=2.6.1
  - pyclipper=1.2.1
  - Pygments=2.8.1
  - pyparsing=2.4.7
  - pytest=6.2.3
  - pytest-cov=2.11.1
  - pytest-html=3.1.1
  - pytest-metadata=1.11.0
  - python-dateutil=2.8.1
  - pytools=2021.2.3
  - pytz=2021.1
  - pyzmq=22.0.3
  - scikit-learn=0.24.1
  - seaborn=0.11.1
  - six=1.15.0
  - sphinx=3.5.4
  - tabulate=0.8.9
  - threadpoolctl=2.1.0
  - toml=0.10.2
  - tornado=6.1
  - traitlets=4.3.3
  - trimesh=3.9.14
  - typing_extensions=3.7.4.3
  - versioneer=0.19
  - wcwidth=0.2.5
  - wrapt=1.12.1
  - zipp=3.4.1
  - pip
  - pip:
    - appnope==0.1.2
    - flake8-bandit==2.1.2
    - gmsh-interop==2021.1
    - ipython-genutils==0.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - matplotlib==3.3.4  # Breaks plotting tests if installed from conda
    - neutronics-material-maker==0.1.11
    - pypet==0.5.1
    - pyquaternion==0.9.9
    - sectionproperties==1.0.8
    - shapely==1.7.1  # conda cannot resolve 1.7.1
    - sphinx-autoapi==1.8.0
    - sphinx-rtd-theme==0.5.2
    - tables==3.6.1
    - -e ..[dev]
