name: bluemira
channels:
  - conda-forge
  - nodefaults

variables:
  # Avoid use of .local
  PYTHONNOUSERSITE: "1"

  # The below settings are needed to support FreeCAD integration alongside click.
  # When adding or changing an environment variable you should consider including it
  # in the environment variables used in the .github/workflows/ci.yml, so as to replicate
  # the user environment as closely as possible (since they don't appear to be loaded
  # into the GitHub Actions shell).
  # NOTE: This may produce a warning when activating the conda environment if overriding
  # the machine's language
  LANG: "C"
  LC_ALL: "C"
  PYTHONIOENCODING: "utf-8"

dependencies:
  - python >=3.10,<3.12
  - fenics-dolfinx=0.7.3
  - freecad=0.21.2
  - h5py
  - openmc>=0.14.0
  - mpi4py<4
  - graphviz
  - pip
  - pip:
      - -r ../requirements/all.txt
      - -r ../requirements/conda.txt
      - -e ../
