name: bluemira
channels:
  - conda-forge
  - nodefaults

variables:
  # Avoid use of .local
  PYTHONNOUSERSITE: '1'

  # The below settings are needed to support FreeCAD integration alongside click.
  # When adding or changing an environment variable you should consider including it
  # in the environment variables used in the .github/workflows/ci.yml, so as to replicate
  # the user environment as closely as possible (since they don't appear to be loaded
  # into the GitHub Actions shell).
  # NOTE: This may produce a warning when activating the conda environment if overriding
  # the machine's language
  LANG: 'C'
  LC_ALL: 'C'
  PYTHONIOENCODING: 'utf-8'

dependencies:
  - python=3.8
  - freecad=0.20.1
  - pivy=0.6.8
  - libpng=1.6.37 # malloc crash on 1.6.38
  - hdf5=1.12.1
  - netcdf4=1.6.0
  - numpy=1.22.4
  - fenics=2019.1.0
  - MeshPy=2020.1
  - meshio=4.4.5
  - mshr=2019.1.0
  - scipy=1.7.3
  - graphviz
  - pip
  - pip:
    - -r ../requirements.txt
    - -r ../requirements-develop.txt
    - -r ../requirements-conda.txt
    - -r ../requirements-examples.txt
