name: bluemira

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.8
  - pythonocc-core=7.5.1
  - freecad=0.19.1
  - numba==0.53.1
  - numpy=1.18.1
  - fluids=0.1.77
  - shapely=1.6.4
  - MeshPy=2018.2.1
  - pyside2=5.13.2
  - scipy=1.4.1
  - pip
  - pip:
    - -r file:../requirements.txt
    - -r file:../requirements-develop.txt
