name: Install Process

inputs:
  version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout process
      uses: actions/checkout@v4
      with:
        repository: "ukaea/process"
        path: "./process"
        ref: ${{ inputs.version }}

    - name: Move process and install dependencies
      id: deps
      shell: bash -l {0}
      run: |
        mv process ../process
        sudo apt-get update && sudo apt-get install -y ninja-build build-essential
        pip install cmake

    - name: Install process
      working-directory: "/home/runner/work/"
      shell: bash -l {0}
      run: |
        cd bluemira/process
        cmake -G Ninja -S . -B build -DRELEASE=TRUE
        cmake --build build
