name: Install Process

inputs:
  version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout process
      uses: actions/checkout@v4
      with:
        repository: "ukaea/process"
        path: "./process"
        ref: ${{ inputs.version }}

    - name: Move process and install dependencies
      id: deps
      shell: bash -l {0}
      run: |
        mv process ../process

    - name: Install process
      working-directory: "/home/runner/work/"
      shell: bash -l {0}
      run: |
        cd bluemira/process
        pip install .
