"""Example of the magnetic field generated by a circular coil"""

import gmsh
import matplotlib.pyplot as plt
import numpy as np
import pyvista
from dolfinx import geometry
from dolfinx.io import XDMFFile
from dolfinx.io.gmshio import model_to_mesh
from dolfinx.plot import create_vtk_mesh
from mpi4py import MPI

from newcode.fem_magnetostatic import FemMagnetostatic2D, create_j_function

rank = MPI.COMM_WORLD.rank

gmsh.initialize()
ri = 0.01  # Inner radius of copper wire
rc = 5  # Outer radius of copper wire
R = 100  # Radius of domain
I_wire = 10e6  # wire's current
gdim = 2  # Geometric dimension of the mesh
model_rank = 0
mesh_comm = MPI.COMM_WORLD

# Define geometry for wire cylinder
lwire = 0.01
lenclo = 3

p1 = gmsh.model.occ.addPoint(0, R, 0, lenclo, 1)
p2 = gmsh.model.occ.addPoint(0, -R, 0, lenclo, 2)
pc = gmsh.model.occ.addPoint(0, 0, 0, lenclo / 50, 3)

wire_w = gmsh.model.occ.addCircle(rc, 0, 0, ri, 1)
gmsh.model.occ.addCurveLoop([wire_w], 1)
wire_f = gmsh.model.occ.addPlaneSurface([1])
gmsh.model.occ.synchronize()

enclo_w1_1 = gmsh.model.occ.addLine(p1, pc, 2)
enclo_w1_2 = gmsh.model.occ.addLine(pc, p2, 3)

enclo_w2 = gmsh.model.occ.addCircle(0, 0, 0, R, 4, 0, np.pi / 2)
enclo_w3 = gmsh.model.occ.addCircle(0, 0, 0, R, 5, 3 * np.pi / 2, 2 * np.pi)
gmsh.model.occ.addCurveLoop([enclo_w1_1, enclo_w1_2, enclo_w2, enclo_w3], 2)
enclo_f = gmsh.model.occ.addPlaneSurface([2, 1])
gmsh.model.occ.synchronize()

gmsh.model.addPhysicalGroup(2, [enclo_f], 0)
gmsh.model.addPhysicalGroup(2, [wire_w], 1)
gmsh.model.occ.synchronize()

# Generate mesh
gmsh.option.setNumber("Mesh.Algorithm", 2)
gmsh.option.setNumber("Mesh.CharacteristicLengthMin", lwire)
gmsh.option.setNumber("Mesh.CharacteristicLengthMax", lenclo)
gmsh.model.mesh.generate(gdim)
gmsh.model.mesh.optimize("Netgen")

mesh, ct, _ = model_to_mesh(gmsh.model, mesh_comm, model_rank, gdim=2)

gmsh.write("Mesh.geo_unrolled")
gmsh.write("Mesh.msh")
gmsh.finalize()


with XDMFFile(MPI.COMM_WORLD, "mt.xdmf", "w") as xdmf:
    xdmf.write_mesh(mesh)
    xdmf.write_meshtags(ct)

pyvista.start_xvfb()

pyvista.OFF_SCREEN = True
plotter = pyvista.Plotter()
grid = pyvista.UnstructuredGrid(*create_vtk_mesh(mesh, mesh.topology.dim))
num_local_cells = mesh.topology.index_map(mesh.topology.dim).size_local
grid.cell_data["Marker"] = ct.values[ct.indices < num_local_cells]
grid.set_active_scalars("Marker")
actor = plotter.add_mesh(grid, show_edges=True)
plotter.view_xy()

if not pyvista.OFF_SCREEN:
    plotter.show()
else:
    cell_tag_fig = plotter.screenshot("cell_tags.png")

em_solver = FemMagnetostatic2D(mesh, ct, ("CG", 2), symmetry="cyl")
j_wire = create_j_function(mesh, ct, [(I_wire, 1)])
em_solver.solve(j_wire)

plotter = pyvista.Plotter()
V = em_solver._V
Psi = em_solver.Psi

B = em_solver.compute_B(("CG", 1))
W = B.function_space

num_points = 1001
z_min = 0
z_max = 10
z = np.linspace(z_min, z_max, num_points)
points = np.zeros((3, num_points))
points[1] = z
Psi_values = []
B_values = []

bb_tree = geometry.BoundingBoxTree(mesh, mesh.topology.dim)
cells = []
points_on_proc = []
# Find cells whose bounding-box collide with the points
cell_candidates = geometry.compute_collisions(bb_tree, points.T)
# Choose one of the cells that contains the point
colliding_cells = geometry.compute_colliding_cells(mesh, cell_candidates, points.T)
for i, point in enumerate(points.T):
    if len(colliding_cells.links(i)) > 0:
        points_on_proc.append(point)
        cells.append(colliding_cells.links(i)[0])
points_on_proc = np.array(points_on_proc, dtype=np.float64)
Psi_values = Psi.eval(points_on_proc, cells)
B_values = B.eval(points_on_proc, cells)

x_new = points_on_proc[:, 1]

B_z_teo = (
    4 * np.pi * 1e-7 * I_wire * rc**2 / (2 * np.sqrt((x_new**2 + rc**2)) ** 3)
)

fig = plt.figure()
plt.plot(x_new, B_values[:, 1], "b--", linewidth=2, label="B")
plt.plot(x_new, B_z_teo, "g-", linewidth=2, label="B_y_teo")

plt.grid(True)
plt.xlabel("x")
plt.legend()
# If run in parallel as a python file, we save a plot per processor
plt.savefig(f"B_Az_rank{MPI.COMM_WORLD.rank:d}.png")
plt.show()

adiff = B_values[:, 1] - B_z_teo
fig = plt.figure()
plt.plot(x_new, adiff, linewidth=2, label="B absolute diff")

plt.grid(True)
plt.xlabel("x")
plt.legend()
# If run in parallel as a python file, we save a plot per processor
plt.savefig(f"B_absolute_diff{MPI.COMM_WORLD.rank:d}.png")

rdiff = (B_values[:, 1] - B_z_teo) / B_z_teo
fig = plt.figure()
plt.plot(x_new, rdiff, linewidth=2, label="B relative diff")

plt.grid(True)
plt.xlabel("x")
plt.legend()
# If run in parallel as a python file, we save a plot per processor
plt.savefig(f"B_relative_diff{MPI.COMM_WORLD.rank:d}.png")
