# SPDX-FileCopyrightText: 2021-present M. Coleman, J. Cook, F. Franza
# SPDX-FileCopyrightText: 2021-present I.A. Maione, S. McIntosh
# SPDX-FileCopyrightText: 2021-present J. Morris, D. Short
#
# SPDX-License-Identifier: LGPL-2.1-or-later

"""
CAD apis
"""

BACKEND = "CadQuery"
# BACKEND = "FREECAD"

if BACKEND == "FREECAD":
    from bluemira.codes.cadapi._freecad.api import (
        apiVertex,
        apiVector,
        apiEdge,
        apiWire,
        apiFace,
        apiShell,
        apiSolid,
        apiShape,
        apiSurface,
        apiPlacement,
        apiPlane,
        apiCompound,
        catch_caderr,
        arrange_edges,
        check_data_type,
        vector_to_list,
        point_to_list,
        vertex_to_list,
        vector_to_numpy,
        point_to_numpy,
        vertex_to_numpy,
        _check_reverse,
        make_wire,
        make_solid,
        make_shell,
        make_compound,
        make_polygon,
        make_bezier,
        make_bspline,
        make_bsplinesurface,
        interpolate_bspline,
        make_circle_curve,
        make_circle,
        make_circle_arc_3P,
        make_ellipse,
        offset_wire,
        make_face,
        _get_api_attr,
        length,
        area,
        volume,
        center_of_mass,
        is_null,
        is_closed,
        is_valid,
        is_same,
        bounding_box,
        optimal_bounding_box,
        tessellate,
        start_point,
        end_point,
        ordered_vertexes,
        vertexes,
        orientation,
        edges,
        ordered_edges,
        wires,
        faces,
        shells,
        solids,
        normal_at,
        wire_closure,
        close_wire,
        discretise,
        discretise_by_edges,
        dist_to_shape,
        wire_value_at,
        wire_parameter_at,
        split_wire,
        _split_edge,
        _get_closest_edge_idx,
        slice_shape,
        _slice_wire,
        _slice_solid,
        import_cad,
        webgl_export,
        stepz_import,
        meshed_exporter,
        save_as_STP,
        _scale_obj,
        save_cad,
        scale_shape,
        translate_shape,
        rotate_shape,
        mirror_shape,
        revolve_shape,
        extrude_shape,
        _split_wire,
        sweep_shape,
        loft,
        fillet_wire_2D,
        boolean_fuse,
        boolean_cut,
        boolean_fragments,
        point_inside_shape,
        _edges_tangent,
        _wire_edges_tangent,
        _wire_is_planar,
        _wire_is_straight,
        _is_wire_or_face,
        _check_shapes_same_type,
        _check_shapes_coplanar,
        _shapes_are_coplanar,
        _shapes_are_coaxis,
        _make_shapes_coaxis,
        fix_shape,
        make_placement,
        make_placement_from_matrix,
        move_placement,
        make_placement_from_vectors,
        change_placement,
        make_plane,
        make_plane_from_3_points,
        face_from_plane,
        plane_from_shape,
        placement_from_plane,
        _colourise,
        collect_verts_faces,
        collect_wires,
        show_cad,
        rotate_into_position,
        embedLight,
        extract_attribute,
        serialise_shape,
        deserialise_shape,
        _convert_edge_to_curve,
        CADFileType,
        JoinType,
        CADFileType,
        DefaultDisplayOptions,
        Document,
        check_wire,
    )

elif BACKEND == "CadQuery":
    from bluemira.codes.cadapi._cadquery.api import (
        apiVertex,
        apiVector,
        apiEdge,
        apiWire,
        apiFace,
        apiShell,
        apiSolid,
        apiShape,
        # apiSurface,
        apiPlacement,
        apiPlane,
        apiCompound,
        catch_caderr,
        # arrange_edges,
        # check_data_type,
        vector_to_list,
        # point_to_list,
        # vertex_to_list,
        vector_to_numpy,
        # point_to_numpy,
        # vertex_to_numpy,
        # _check_reverse,
        make_wire,
        make_solid,
        make_shell,
        make_compound,
        make_polygon,
        make_bezier,
        make_bspline,
        make_bsplinesurface,
        interpolate_bspline,
        make_circle_curve,
        make_circle,
        make_circle_arc_3P,
        make_ellipse,
        offset_wire,
        make_face,
        _get_api_attr,
        length,
        area,
        volume,
        center_of_mass,
        is_null,
        is_closed,
        is_valid,
        is_same,
        bounding_box,
        # optimal_bounding_box,
        tessellate,
        start_point,
        end_point,
        # ordered_vertexes,
        vertexes,
        # orientation,
        edges,
        # ordered_edges,
        wires,
        faces,
        shells,
        solids,
        normal_at,
        wire_closure,
        close_wire,
        discretise,
        discretise_by_edges,
        # dist_to_shape,
        # wire_value_at,
        # wire_parameter_at,
        # split_wire,
        # _split_edge,
        # _get_closest_edge_idx,
        # slice_shape,
        # _slice_wire,
        # _slice_solid,
        # import_cad,
        # webgl_export,
        # stepz_import,
        # meshed_exporter,
        # save_as_STP,
        # _scale_obj,
        # save_cad,
        # scale_shape,
        # translate_shape,
        # rotate_shape,
        # mirror_shape,
        # revolve_shape,
        # extrude_shape,
        # _split_wire,
        # sweep_shape,
        # loft,
        # fillet_wire_2D,
        # boolean_fuse,
        # boolean_cut,
        # boolean_fragments,
        # point_inside_shape,
        # _edges_tangent,
        # _wire_edges_tangent,
        # _wire_is_planar,
        # _wire_is_straight,
        # _is_wire_or_face,
        # _check_shapes_same_type,
        # _check_shapes_coplanar,
        # _shapes_are_coplanar,
        # _shapes_are_coaxis,
        # _make_shapes_coaxis,
        # fix_shape,
        make_placement,
        make_placement_from_matrix,
        # move_placement,
        # make_placement_from_vectors,
        # change_placement,
        # make_plane,
        # make_plane_from_3_points,
        # face_from_plane,
        # plane_from_shape,
        # placement_from_plane,
        # _colourise,
        # collect_verts_faces,
        # collect_wires,
        show_cad,
        # rotate_into_position,
        # embedLight,
        # extract_attribute,
        # serialise_shape,
        # deserialise_shape,
        # _convert_edge_to_curve,
        JoinType,
        CADFileType,
        DefaultDisplayOptions,
        # Document,
        check_wire,
    )

from bluemira.codes.cadapi.error import CADError

__all__ = ["cadapi", "CADError"]
