name: blueprint_ci

on:
  push:
    branches:
      - master
      - develop
      - 8-github-actions

jobs:
  build-and-test:

    runs-on: self-hosted

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if conda/environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_packages_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
          hashFiles(
            'conda/environment.yml',
            'requirements.txt',
            'requirements-develop.txt',
            'setup.py'
          ) }}

    - name: install_env
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: bluemira
        environment-file: conda/environment.yml
        miniforge-version: "latest"
        use-only-tar-bz2: true

    - name: pytest
      run: |
        DISPLAY=
        pytest tests --cov-report=term --reactor

    - name: code_quality
      run: |
        flake8 --count
        black --check .

    - name: docs
      run: |
        sphinx-build documentation/source documentation/build
