name: blueprint_ci

on:
  push:
    branches:
      - master
      - develop
      - 8-github-actions

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache pip
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if requirements.txt has not changed
        PIP_CACHE_NUMBER: 1
      with:
        path: ~/.cache/pip
        key: 
          ${{ runner.os }}-pip-${{ env.PIP_CACHE_NUMBER }}-${{
          hashFiles('requirements.txt', 'requirements-develop.txt', 'setup.py') }}


    - name: Cache conda
      uses: actions/cache@v2
      env:
        # Increase this value to reset cache if conda/environment.yml has not changed
        CONDA_CACHE_NUMBER: 1
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CONDA_CACHE_NUMBER }}-${{
          hashFiles(
            'conda/environment.yml',
            'requirements.txt',
            'requirements-develop.txt',
            'setup.py'
          ) }}

    - name: Install Environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: bluemira
        environment-file: conda/environment.yml
        miniforge-version: "latest"
        use-only-tar-bz2: true

    - name: Run pytest
      run: |
        unset DISPLAY
        conda activate bluemira
        pytest tests --cov-report=term --reactor

    - name: Check Code Quality
      run: |
        flake8 --count BLUEPRINT examples tests
        black --check BLUEPRINT examples tests

    - name: Build Documentation
      run: |
        sphinx-build documentation/source documentation/build
