name: PR Comments

# This workflow should only be used for low permission actions
# for instance those that don't need the repository checked out.
on:
  workflow_run:
    workflows: ["bluemira_ci"]
    types:
      - completed

jobs:
  warnings-comment:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Download reference test report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        artifact_url="$( \
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name == "report-json") | select(.workflow_run.head_sha == "${{ github.event.workflow_run.pull_request.base.sha }}") | .archive_download_url')"
        if [ ! -z "${artifact_url}" ]; then
          gh api ${artifact_url} > report-json.zip
          mkdir ref_report
          unzip report-json.zip -d ref_report
        fi
    - name: Download PR test report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        artifact_url="$( \
          gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name == "report-json") | select(.workflow_run.head_sha == "${{ github.event.workflow_run.head_sha }}") | .archive_download_url')"
        if [ ! -z "${artifact_url}" ]; then
          gh api ${artifact_url} > report-json.zip
          mkdir PR_report
          unzip report-json.zip -d PR_report
        fi
    - name: Generate warning report
      if: ${{ github.event_name == 'pull_request' }}
      id: warning-report
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        if [ -f "ref_report/.report.json" ]; then
          compare_args="--compare ref_report/.report.json"
        fi
        report_str=$(python scripts/format_warning_report.py PR_report/.report.json ${compare_args}) || true
        # Ugly stuff to escape new lines
        report_str="${report_str//'%'/'%25'}"
        report_str="${report_str//$'\n'/'%0A'}"
        echo "::set-output name=report::"${report_str}""

    - name: Find warning report comment
      uses: peter-evans/find-comment@v2
      id: find-warning-report-comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        issue-number: ${{ github.event.workflow_run.pull_request.number }}
        comment-author: "github-actions[bot]"
        body-includes: ⚠️ Warning Report
        direction: last

    - name: Create or update warning report comment
      uses: peter-evans/create-or-update-comment@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        comment-id: ${{ steps.find-warning-report-comment.outputs.comment-id }}
        issue-number: ${{ github.event.workflow_run.pull_request.number }}
        body: ${{ steps.warning-report.outputs.report }}
        edit-mode: replace
