name: Open dependencies PR

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "New semantic version string"
        required: true

jobs:
  dep_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}

      - name: Permissions Check
        uses: Fusion-Power-Plant-Framework/fppf-actions/permission_check@89a6a6cda086f015357aeab38c270da3dd8861ed
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}

      - name: Open develop_dependencies PR
        uses: ./.github/workflows/actions/dependencies_PR
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}
          tag: ${{ inputs.version }}
