name: Open dependencies PR

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "New semantic version string"
        required: true

jobs:
  dep_pr:
    steps:
      - name: Permissions Check
        uses: ./.github/workflows/perm
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}
      - name: Open develop_dependencies PR
        if: ${{ inputs.open_dependencies_pr && !inputs.draft }}
        uses: ./.github/workflows/deps_PR
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}
          tag: ${{ inputs.version }}
