name: docker
permissions: read-all
on:
  push:
    tags:
      - "v*"
  schedule:
    - cron: "29 18 * * 1" # Every Monday at 18:29

jobs:
  deploy_conda_image:
    runs-on: ubunut-latest
    steps:
      - name: Determine bluemira version and Docker tag
        id: versions
        run: |
          if [[ "${GITHUB_EVENT_NAME}" == "schedule" ]]; then
            echo "image_tag=develop" >> $GITHUB_OUTPUT
            echo "checkout_ref=develop" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "image_tag=${TAG_NAME:1}" >> $GITHUB_OUTPUT
            echo "checkout_ref=${TAG_NAME}" >> $GITHUB_OUTPUT
          else
            echo "invalid git ref: image tag could not be determined"
            exit 1
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.versions.outputs.checkout_ref }}

      # We need the currently checked out revision of the repository, not the
      # one from the CI trigger. Use `git rev-parse` instead of `GITHUB_SHA`.
      - name: Get Git revision
        id: revision
        run: echo "bluemira_revision=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io/fusion-power-plant-framework/bluemira
          username: ${{ secrets.QUAY_ID }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          file: ./docker/conda.Dockerfile
          tags: quay.io/fusion-power-plant-framework/bluemira:${{ steps.versions.outputs.image_tag }}
          build-args: |
            BLUEMIRA_VERSION=${{ steps.versions.outputs.image_tag }}
            BLUEMIRA_REVISION=${{ steps.revision.outputs.bluemira_revision }}
            PROCESS_VERSION=v3.1.0
