# Runs the bluemira examples and checks for errors
name: bluemira_examples

on:
  workflow_dispatch:
  schedule:
    # Runs every Monday at 04:37
    - cron: "37 4 * * 1"
  pull_request:
    paths:
      - examples/**
  push:
    paths:
      - examples/**
    branches:
      - develop
      - main

jobs:
  examples:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11", "3.12"]
        process-version: ["v3.4.1"]

      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        uses: ./.github/workflows/actions/build
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PROCESS
        if: ${{ matrix.process-version!= 'process_disabled' }}
        uses: ./.github/workflows/actions/process
        with:
          version: ${{ matrix.process-version }}

      - name: Setup headless graphics
        uses: pyvista/setup-headless-display-action@57ebfcf63dee3d902a83d1d613301404c1d3b736 # v4.3

      - name: Run examples
        shell: bash -l {0}
        run: |
          # Exclude examples using plasmod or process, as these aren't available
          # to the CI runners
          # Reasons:
          # requires plasmod
          # doesnt currently converge
          # requires plasmod
          # not an example
          # needs improvement #2999
          python ./scripts/run_examples.py \
            -e 'plasmod_example' \
            -e 'equilibria/fem_fixed_boundary' \
            -e 'codes/ext_code_script' \
            -e 'radiation_transport/run_cad_neutronics'
