name: PR develop -> main

on:
  push:
    branches:
      - james/release_workflow
  # schedule:
  #   # Runs every Monday at 06:15
  #   - cron: "15 6 * * 0"

jobs:
  check-release-date:
    # We want to run the 'open-pr-develop-into-main' job every 6 weeks, but I
    # don't know of a way to do this through the cron standard used. Instead,
    # use this job to decide whether the current date is a multiple of 6 weeks
    # from our initial release date.
    outputs:
      release_due: ${{ steps.check-release-due.outputs.release_due }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Date
        id: check-release-due
        run: |
          INITIAL_RELEASE_DATE="$(date --date="220414" +%s)"
          # INITIAL_RELEASE_DATE="$(date --date="220530" +%s)"
          CURRENT_DATE="$(date --date="$(date +'%y%m%d')" +%s)"
          DAYS_DIFF=$(( ("${INITIAL_RELEASE_DATE}" - "${CURRENT_DATE}")/(60*60*24) ))
          if [ $(("${DAYS_DIFF}" % 42)) -eq 0 ]; then
            echo ::set-output name=release_due::true
          else
            echo ::set-output name=release_due::false
          fi

  open-pr-develop-into-main:
    runs-on: ubuntu-latest
    needs: check-release-date
    if: ${{ needs.check-release-date.outputs.release_due == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create pull request
        run: >
          HEAD="develop" &&
          BASE="main" &&
          gh pr create \
            --head "${HEAD}" \
            --base "${BASE}" \
            --title "Merge develop into main for a new release" \
            --body "Update main with changes on develop in preparation for a release." \
            --label "automatic" \
            --label "release" \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
