name: PR develop -> main

on:
  schedule:
    # Runs every Monday at 06:15
    - cron: "15 6 * * 0"

jobs:
  check-date:
    # We want to run the 'open-pr' job every 6 weeks, but I don't know of a way
    # to do this through the cron standard used. Instead, use this job to
    # decide whether the current date is a multiple of 6 weeks from our first
    # release date.
    outputs:
      release_date: ${{ steps.check.a_release_date }}
    runs-on: ubuntu-latest
    steps:
      - name: Check Date
        id: check
        run: |
          INITIAL_RELEASE_DATE="$(date --date="220530" +%s)"
          CURRENT_DATE="$(date --date="$(date +'%y%m%d')" +%s)"
          DAYS_DIFF=$(( ("${INITIAL_RELEASE_DATE}" - "${CURRENT_DATE}")/(60*60*24) ))
          if [ $(("${DAYS_DIFF}" % 42)) -eq 0 ]; then
            ::set-output name=a_release_date::true
          else
            ::set-output name=a_release_date::false
          fi

  open-pr:
    runs-on: ubuntu-latest
    needs: check-date
    if: ${{ needs.check.outputs.a_release_date == 'true' }}
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          HEAD="develop" &&
          BASE="main" &&
          git pull origin "${HEAD}" "${BASE}" &&
          gh pr create
            --head "${HEAD}"
            --base "${BASE}"
            --title "Prepare main for new release"
            --body "Update main with changes on develop in preparation for a release."
            --reviewer "@Fusion-Power-Plant-Framework/repo-review"
            --label "automatic"
            --label "release"
