name: Update pinned dependencies

on:
  workflow_dispatch:

jobs:
  dep_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}

      - name: Permissions Check
        uses: ./.github/workflows/actions/permission_check
        with:
          token: ${{ secrets.FPPF_BOT_AUTH_KEY }}

      - uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Run uv
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip compile pyproject.toml --extra pinned -o requirements/base.txt
          uv pip compile pyproject.toml --extra pinned -o requirements/develop.txt --extra dev
          uv pip compile pyproject.toml --extra pinned -o requirements/examples.txt --extra examples
          uv pip compile pyproject.toml --extra pinned -o requirements/all.txt --extra dev --extra polyscope --extra radiation --extra examples
