name: bluemira release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "New semantic version string"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        id: create_a_release
        run: |
          pip install packaging
          VERSION=$(python scripts/version_checker.py ${{ version }})
          TAG="v${VERSION}"
          git checkout main
          git tag -s -a "${TAG}" -m "🍻 Version ${VERSION}"
          git push origin "${TAG}"

          echo ::set-output name=tag::${TAG}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create PR to update dependencies
        with:
          tag: ${{ steps.create_a_release.outputs.tag }}
        run: >
          gh pr create \
            --head develop_dependencies \
            --base develop \
            --title "Dependency update after ${INPUT_TAG}" \
            --body "Update develop's dependencies for the next development cycle." \
            --reviewer "repo-review" \
            --label "automatic" \
            --label "dependencies"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
