name: bluemira release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "New semantic version string"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update main
        id: update-main
        run: |
          git fetch origin main develop
          git checkout main
          git merge origin/develop --ff-only
          git push origin main

      - name: Tag release
        id: tag-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install packaging
          VERSION="$(python -c "from packaging import version; print(version.Version(\"${{ github.event.inputs.version }}\"))")"
          TAG="v${VERSION}"
          git checkout main
          git config user.email "fusion-power-plant-framework@protonmail.com"
          git config user.name "fusion-power-plant-framework"
          git tag -a "${TAG}" -m "🍻 Version ${VERSION}"
          git push origin "${TAG}"

          echo ::set-output name=tag::${TAG}

      - name: Update develop dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin develop_dependencies
          git switch develop_dependencies --force
          git rebase origin/develop -S
          git push origin develop_dependencies --force-with-lease

      - name: Create PR to update dependencies
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          gh pr create \
            --head develop_dependencies \
            --base develop \
            --title "Dependency update after ${{ steps.tag-release.outputs.tag }}" \
            --body "Update develop's dependencies for the next development cycle."
          gh pr review \
            --request-changes
            --body "This is an auto-generated PR that requires a fast-forward merge. Please comment '/fast-forward' to trigger the merge."
