name: Make Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "New semantic version string"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate
        id: validate
        run: |
          # Check, and format, input version
          pip install packaging
          VERSION="$(python -c "from packaging import version; print(version.Version(\"${{ github.event.inputs.version }}\"))")"
          TAG="v${VERSION}"

          # Check the tag doesn't already exist
          if gh release view "${TAG}" &> /dev/null; then
            echo "Release with tag '${TAG}' already exists.";
            exit 1;
          fi

          echo ::set-output name=tag::${TAG}

      - name: Update main
        id: update-main
        run: |
          git fetch origin main develop
          git checkout main
          git merge origin/develop --ff-only
          git push origin main

      - name: Create release
        id: create-release
        run: |
          gh release create "${{ steps.validate.outputs.tag }}" \
            --generate-notes \
            --target main

      - name: Fast-forward develop_dependencies
        run: |
          # Update develop_dependencies by checking out develop, fast-forward
          # merging, and then pushing back to develop_dependencies.
          # This is similar to a rebase, but ensures no history is re-written,
          # and signed commits are persisted.
          git switch develop --force
          git checkout -b develop_with_deps
          git fetch origin develop_dependencies
          git merge origin/develop_dependencies --ff-only
          git push --force-with-lease origin develop_with_deps:develop_dependencies

      - name: Create PR to update dependencies
        run: |
          PR_URL=$(gh pr create \
            --head develop_dependencies \
            --base develop \
            --title "Dependency update after ${{ steps.validate.outputs.tag }}" \
            --body "Update develop's dependencies for the next development cycle.")
          gh pr comment "${PR_URL}" \
            --body "**Reminder that this PR must be merged using a merge commit!**"
